# Generated by Django 5.2.9 on 2026-03-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_alter_notification_notif_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('enrollment_success', 'Enrollment Berhasil'), ('payment_success', 'Pembayaran Berhasil'), ('payment_failed', 'Pembayaran Gagal'), ('new_lesson', 'Materi Baru'), ('new_quiz', 'Quiz/Tugas Baru'), ('deadline_reminder', 'Pengingat Deadline'), ('progress_milestone', 'Pencapaian Progress'), ('certificate_issued', 'Sertifikat Diterbitkan'), ('instructor_announcement', 'Pengumuman dari Pengajar'), ('new_review', 'Review Baru pada Course-mu'), ('submission_received', 'Submission Reviewed'), ('new_course_comment', 'New Course Comment'), ('partner_request_submitted', 'Partner Request Submitted'), ('partner_request_resubmitted', 'Partner Request Resubmitted'), ('partner_approved', 'Partner Approved'), ('partner_rejected', 'Partner Rejected'), ('partner_revision', 'Partner Revision Required'), ('assigned_course_instructor', 'Assigned Course Instructor'), ('course_submitted', 'Course Submitted'), ('course_ready_publish', 'Course Ready for Publish'), ('course_rejected_partner', 'Course Rejected by Partner'), ('course_rejected_superuser', 'Course Rejected by Superuser'), ('course_published', 'Course Published')], max_length=40),
        ),
    ]
