# Generated by Django 5.2.9 on 2026-01-23 08:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='last_comment_checked',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
