# Generated by Django 5.2.1 on 2025-11-20 03:39

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0066_alter_pricingtype_options_alter_pricingtype_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text'),
        ),
    ]
