# Generated by Django 5.2.9 on 2026-01-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0070_alter_coursesessionlog_duration_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
