# Generated by Django 5.2.9 on 2026-01-27 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0072_sectionreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionreport',
            name='message',
        ),
        migrations.AlterField(
            model_name='sectionreport',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.assessment'),
        ),
        migrations.AlterField(
            model_name='sectionreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='sectionreport',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.material'),
        ),
        migrations.AlterField(
            model_name='sectionreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved')], db_index=True, default='pending', max_length=20),
        ),
    ]
