# Generated by Django 5.2.9 on 2026-01-27 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0073_remove_sectionreport_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='readiness_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CourseChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='courses.course')),
            ],
        ),
    ]
