# Generated by Django 5.2.9 on 2026-03-31 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0075_alter_quiz_question_type_assessmentresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='access_type',
            field=models.CharField(choices=[('public', 'Public'), ('invite_only', 'Invite Only')], default='public', max_length=20),
        ),
    ]
