# Generated by Django 5.2.9 on 2026-01-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_customuser_education_alter_customuser_gender'),
        ('courses', '0069_video_quiz_option_quizresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='users_with_interest', to='courses.category'),
        ),
    ]
