# forms.py
import requests
import xml.etree.ElementTree as ET
import re
from django.core.validators import URLValidator
from django.core.exceptions import ValidationError
from django import forms
from django.forms import inlineformset_factory
from django.core.cache import cache
from .models import CourseTeam,MicroCredentialComment,LTIExternalTool1,MicroCredentialReview,Course,SosPost,CourseStatus,CourseRating,MicroCredential, AskOra,Partner,Category, Section,Instructor,TeamMember,GradeRange, Material,Question, Choice,Assessment,PricingType, CoursePrice
from django_ckeditor_5.widgets import CKEditor5Widget
import os
from authentication.models import CustomUser, Universiti
import logging
from django.utils.text import slugify
from django.core.files.base import ContentFile
from PIL import Image as PILImage
import io
from datetime import date
from django.core.exceptions import ValidationError
from django.utils import timezone
from captcha.fields import CaptchaField
import xml.etree.ElementTree as ET
import hashlib
from django_select2.forms import ModelSelect2MultipleWidget
from dal import autocomplete
from decimal import Decimal
from django.utils.safestring import mark_safe
from datetime import date, timedelta
logger = logging.getLogger(__name__)





class MicroCredentialCommentForm(forms.ModelForm):
    class Meta:
        model = MicroCredentialComment
        fields = ['content']  # Form hanya meminta konten komentar

    def __init__(self, *args, **kwargs):
        super(MicroCredentialCommentForm, self).__init__(*args, **kwargs)
        self.fields['content'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Write your comment here...'})

class MicroCredentialReviewForm(forms.ModelForm):
    class Meta:
        model = MicroCredentialReview
        fields = ['rating', 'review_text']
        widgets = {
            'review_text': forms.Textarea(attrs={'rows': 4, 'placeholder': 'Write your review here...'}),
        }
        
class LTIExternalToolForm(forms.ModelForm):
    class Meta:
        model = LTIExternalTool1
        fields = [
            'tool_name',
            'launch_url',
            'tool_url',
            'consumer_key',
            'shared_secret',
            'custom_parameters',
        ]
        labels = {
            'tool_name': 'Tool Name',
            'launch_url': 'Launch URL',
            'tool_url': 'Tool URL (optional)',
            'consumer_key': 'Consumer Key',
            'shared_secret': 'Shared Secret',
            'custom_parameters': 'Custom Parameters',
        }
        help_texts = {
            'launch_url': 'LTI launch URL provided by the external tool.',
            'tool_url': 'Optional homepage or tool info URL.',
            'consumer_key': 'Provided by the LTI platform.',
            'shared_secret': 'Provided or generated by the LTI platform.',
            'custom_parameters': 'Optional: One key=value per line.',
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Tailwind base class for input fields
        base_input_class = (
            "w-full px-4 py-2 border border-gray-300 rounded-lg "
            "focus:ring-2 focus:ring-blue-500 focus:outline-none text-gray-800"
        )

        # Tailwind class for textarea
        base_textarea_class = (
            "w-full px-4 py-2 border border-gray-300 rounded-lg "
            "focus:ring-2 focus:ring-blue-500 focus:outline-none text-gray-800"
        )

        for name, field in self.fields.items():
            if isinstance(field.widget, forms.Textarea):
                field.widget.attrs['class'] = base_textarea_class
            else:
                field.widget.attrs['class'] = base_input_class

        # Placeholders
        self.fields['tool_name'].widget.attrs.update({
            'placeholder': 'e.g., H5P, Labster, Moodle Quiz Tool'
        })
        self.fields['launch_url'].widget.attrs.update({
            'placeholder': 'https://provider.com/lti/launch'
        })
        self.fields['tool_url'].widget.attrs.update({
            'placeholder': 'https://provider.com'
        })
        self.fields['consumer_key'].widget.attrs.update({
            'placeholder': 'Enter the consumer key provided by the tool'
        })
        self.fields['shared_secret'].widget.attrs.update({
            'placeholder': 'Enter the shared secret'
        })
        self.fields['custom_parameters'].widget.attrs.update({
            'placeholder': 'key1=value1\nkey2=value2\n(optional)',
            'rows': 4,
        })



class CourseRatingForm(forms.ModelForm):
    class Meta:
        model = CourseRating
        fields = ['rating', 'comment']
        widgets = {
            'rating': forms.Select(attrs={
                'class': 'block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring focus:ring-blue-200 focus:ring-opacity-50'
            }),
            'comment': forms.Textarea(attrs={
                'class': 'block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring focus:ring-blue-200 focus:ring-opacity-50',
                'rows': 3
            }),
        }


class SosPostForm(forms.ModelForm):
    
    class Meta:
        model = SosPost
        fields = ['content']
        widgets = {
            'content': forms.Textarea(attrs={
                'rows': 2,
                'maxlength': 150,
                'class': (
                    'w-full px-4 py-3 text-gray-900 placeholder-gray-400 '
                    'border border-gray-300 rounded-lg focus:ring-2 focus:ring-red-500 '
                    'focus:outline-none text-base resize-none'
                ),
                
                'hx-target': '#post-list',
                'hx-swap': 'prepend'
            }),
        }

    def clean_content(self):
        content = self.cleaned_data['content']
        if len(content) > 150:
            raise forms.ValidationError("Maksimum 150 karakter!")
        return content


class MicroCredentialForm(forms.ModelForm):
    description = forms.CharField(widget=CKEditor5Widget(config_name="extends"))

    class Meta:
        model = MicroCredential
        fields = [
            'title', 'slug', 'description', 'required_courses', 
            'status', 'start_date', 'end_date', 'image', 'category', 
            'min_total_score'
        ]
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'w-full text-lg px-4 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-red-500 outline-none',
                'oninput': 'listingslug(value)',
            }),
            'slug': forms.HiddenInput(attrs={'maxlength': '200'}),
            'description': forms.Textarea(attrs={
                'class': 'w-full px-4 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-red-500 outline-none',
                'rows': 4
            }),
            'start_date': forms.DateInput(attrs={
                'class': 'w-full px-4 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-purple-500 outline-none',
                'type': 'date'
            }),
            'end_date': forms.DateInput(attrs={
                'class': 'w-full px-4 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-purple-500 outline-none',
                'type': 'date'
            }),
            'status': forms.Select(attrs={
                'class': 'w-full px-4 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-indigo-500 outline-none'
            }),
            'required_courses': autocomplete.ModelSelect2Multiple(
                url='courses:course-autocomplete',
                attrs={'class': 'w-full px-4 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-indigo-500 outline-none'}
            ),
            'category': forms.Select(attrs={
                'class': 'w-full px-4 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-indigo-500 outline-none'
            }),
            'min_total_score': forms.NumberInput(attrs={
                'class': 'w-full px-4 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-indigo-500 outline-none',
                'step': '0.1'
            }),
            'image': forms.ClearableFileInput(attrs={
                'class': 'w-full text-sm text-gray-700 border border-gray-300 rounded-md cursor-pointer focus:outline-none'
            }),
        }

class AskOraForm(forms.ModelForm):
    class Meta:
        model = AskOra
        fields = ['title','question_text','response_deadline']  # Menyesuaikan field dengan model AskOra
        
        widgets = {
            'title': forms.TextInput(
                attrs={
                    'class': 'w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:outline-none',
                    'placeholder': 'Title'
                }
            ),

            "question_text": CKEditor5Widget(
                attrs={
                    "class": "django_ckeditor_5 w-full border border-gray-300 rounded-lg",
                },
                config_name="extends",
            ),

            'response_deadline': forms.DateTimeInput(
                attrs={
                    'class': 'w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:outline-none',
                    'placeholder': 'Select response deadline',
                    'type': 'datetime-local'
                }
            ),
        }

        def clean_response_deadline(self):
            response_deadline = self.cleaned_data['response_deadline']
            if response_deadline < timezone.now():
                raise ValidationError("The response deadline cannot be in the past.")
            return response_deadline

#form re-runs
class CourseRerunForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['course_number', 'category', 'level', 'course_run']

    course_name_hidden = forms.CharField(required=False, widget=forms.HiddenInput())
    org_partner_hidden = forms.ModelChoiceField(queryset=Partner.objects.all(), required=False, widget=forms.HiddenInput())

    # Editable fields
    course_number = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'style': 'width: 100%'}))  
    course_run = forms.CharField(max_length=250, widget=forms.TextInput(attrs={'class': 'form-control', 'style': 'width: 100%'}))

    category = forms.ModelChoiceField(queryset=Category.objects.all(), widget=forms.Select(attrs={'class': 'form-control', 'style': 'width: 100%'}))
    level = forms.ChoiceField(choices=[('basic', 'Basic'), ('middle', 'Middle'), ('advanced', 'Advanced')], widget=forms.Select(attrs={'class': 'form-control', 'style': 'width: 100%'}))



class CoursePriceForm(forms.ModelForm):
    class Meta:
        model = CoursePrice
        fields = ['partner_price', 'discount_percent', 'price_type']

        widgets = {
            'partner_price': forms.NumberInput(attrs={
                'class': 'w-full px-3 py-2 border border-gray-300 rounded-lg '
                        'focus:outline-none focus:ring-2 focus:ring-blue-500',
                'placeholder': 'Masukkan harga...',
                'min': '0',
                'step': '0.01',
            }),
            'discount_percent': forms.NumberInput(attrs={
                'class': 'w-full px-3 py-2 border border-gray-300 rounded-lg '
                        'focus:outline-none focus:ring-2 focus:ring-blue-500',
                'placeholder': 'Masukkan diskon...',
                'min': '0',
                'max': '100',
                'step': '0.01',
            }),
            'price_type': forms.Select(attrs={
                'class': 'w-full px-3 py-2 border border-gray-300 rounded-lg '
                        'bg-white focus:outline-none focus:ring-2 focus:ring-blue-500'
            }),
        }


    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

        # Misal, non-partner tidak boleh edit harga & diskon
        if not getattr(self.user, 'is_partner', False):
            self.fields['partner_price'].disabled = True
            self.fields['discount_percent'].disabled = True

    def clean(self):
        cleaned_data = super().clean()
        price_type = cleaned_data.get('price_type')
        partner_price = cleaned_data.get('partner_price')
        discount = cleaned_data.get('discount_percent')

        if price_type and price_type.code == 'free':
            # Jika harga free, harga dan diskon otomatis 0
            cleaned_data['partner_price'] = Decimal('0.00')
            cleaned_data['discount_percent'] = Decimal('0.00')
        else:
            if partner_price is None or partner_price <= 0:
                self.add_error('partner_price', 'Harga wajib diisi dan harus lebih dari 0 untuk harga non-free.')

            if discount is None:
                cleaned_data['discount_percent'] = Decimal('0.00')
            elif discount < 0 or discount > 100:
                self.add_error('discount_percent', 'Diskon harus antara 0 dan 100.')

        return cleaned_data


class CourseInstructorForm(forms.ModelForm):
    instructor = forms.ModelChoiceField(
        queryset=Instructor.objects.none(),
        widget=autocomplete.ModelSelect2(url='courses:instructor-autocomplete'),  # Ganti widget jadi ModelSelect2 dengan URL autocomplete
        required=True,
    )

    class Meta:
        model = Course
        fields = ['instructor']

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super().__init__(*args, **kwargs)

        if self.request and self.request.user.is_authenticated:
            user = self.request.user
            if user.is_superuser:
                self.fields['instructor'].queryset = Instructor.objects.all()
            elif hasattr(user, 'is_partner') and user.is_partner:
                self.fields['instructor'].queryset = Instructor.objects.filter(provider__user=user)
            elif hasattr(user, 'is_instructor') and user.is_instructor:
                self.fields['instructor'].queryset = Instructor.objects.none()

    def clean_instructor(self):
        instructor = self.cleaned_data.get('instructor')
        if not instructor:
            raise forms.ValidationError("Please select a valid instructor.")
        return instructor


class GradeRangeForm(forms.ModelForm):
    class Meta:
        model = GradeRange
        fields = ['name', 'min_grade', 'max_grade']
        widgets = {
            'name': forms.TextInput(attrs={
                'placeholder': 'Enter name of assessment here',
                'class': 'form-control'
            }),
            'min_grade': forms.NumberInput(attrs={
                'placeholder': '0',
                'class': 'form-control',
                'type': 'number',
                'min': '0',  # Optional: Add minimum value
                'max': '100',  # Optional: Add maximum value
            }),
            'max_grade': forms.NumberInput(attrs={
                'placeholder': '0',
                'class': 'form-control',
                'type': 'number',
                'min': '0',  # Optional: Add minimum value
                'max': '100',  # Optional: Add maximum value
            }),
        }



class AssessmentForm(forms.ModelForm):
    class Meta:
        model = Assessment
        fields = ['name', 'weight', 'flag', 'duration_in_minutes']

        widgets = {
            'name': forms.TextInput(attrs={
                'placeholder': 'input assessment name here',
                'class': 'w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none transition',
            }),
            'weight': forms.NumberInput(attrs={
                'placeholder': '0',
                'min': '0',
                'max': '100',
                'class': 'w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none transition',
            }),
            'duration_in_minutes': forms.NumberInput(attrs={
                'placeholder': 'Contoh: 60',
                'min': '0',
                'class': 'w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none transition',
            }),
            'flag': forms.CheckboxInput(attrs={
                'class': 'w-5 h-5 text-blue-600 rounded focus:ring-blue-500 border-gray-300',
            }),
        }

        labels = {
            'name': 'Name Assessment',
            'weight': 'Weight (%)',
            'flag': 'Activate Rich Text Editor',
            'duration_in_minutes': 'Duration (minutes)',
        }

        help_texts = {
            'weight': 'Weight in percent (0–100). Example: 30',
            'duration_in_minutes': 'Duration in minutes. Leave blank if no time limit.',
            'flag': 'Check if you want to enable rich text editor during input.',
        }

    # Validasi tetap sama
    def clean_weight(self):
        weight = self.cleaned_data.get('weight')
        if weight is not None and (weight < 0 or weight > 100):
            raise forms.ValidationError("Weight must be between 0 and 100.")
        return weight

    def clean_duration_in_minutes(self):
        duration = self.cleaned_data.get('duration_in_minutes')
        if duration is not None and duration < 0:
            raise forms.ValidationError("Duration cannot be negative.")
        return duration

class QuestionForm(forms.ModelForm):
    text = forms.CharField(required=True, widget=forms.Textarea)  # Default widget sementara

    class Meta:
        model = Question
        fields = ['text']

    def __init__(self, *args, **kwargs):
        assessment = kwargs.pop('assessment', None)
        super().__init__(*args, **kwargs)

        if assessment and getattr(assessment, 'flag', False):
            self.fields['text'].widget = CKEditor5Widget(config_name="extends")
        else:
            self.fields['text'].widget = forms.Textarea(attrs={
                'class': 'w-full px-6 py-4 text-lg border-2 border-gray-300 rounded-xl focus:border-indigo-600 focus:outline-none transition-shadow focus:ring-4 focus:ring-indigo-100',
                'rows': 6,
                'placeholder': 'Tulis pertanyaan di sini...',
                'style': 'resize: vertical; min-height: 160px;'
            })


# forms.py
class ChoiceForm(forms.ModelForm):
    # Field tambahan hanya untuk tampilan
    is_correct_radio = forms.BooleanField(
        required=False,
        widget=forms.CheckboxInput(attrs={'class': 'hidden'}),
        label=''
    )

    class Meta:
        model = Choice
        fields = ['text', 'is_correct']
        labels = {
            'text': '',
            'is_correct': '',
        }
        

    def __init__(self, *args, **kwargs):
        self.assessment = kwargs.pop('assessment', None)
        super().__init__(*args, **kwargs)

        # Hidden field untuk is_correct asli
        self.fields['is_correct'].widget = forms.HiddenInput()

        # CKEditor atau textarea biasa
        if self.assessment and getattr(self.assessment, 'flag', False):
            self.fields['text'].widget = CKEditor5Widget(config_name='extends')
        else:
            self.fields['text'].widget = forms.Textarea(attrs={
                'class': 'w-full p-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-400 focus:border-indigo-500 transition',
                'rows': 4,
                'placeholder': 'Tulis jawaban...'
            })

        # ⛔ PENTING: biar form baru tidak wajib diisi
        self.empty_permitted = True



# Formset — tetap sama, tapi sekarang benar-benar bersih!
ChoiceFormSet = inlineformset_factory(
    Question,
    Choice,
    form=ChoiceForm,
    fields=['text', 'is_correct'],
    extra=1,
    can_delete=True,
    max_num=10,  # opsional, biar tidak kebanyakan
)
#add section
class SectionForm(forms.ModelForm):
    class Meta:
        model = Section
        fields = ['title','courses','parent']

class MatrialForm(forms.ModelForm):
    #description = forms.CharField(widget=CKEditor5Widget())
    class Meta:
        model = Material
        fields = ['title','description']
        widgets = {
            
            'title': forms.TextInput(attrs={'placeholder': 'Enter short title here', 'class': 'block w-full px-4 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm'}),
            "description": CKEditor5Widget(
                attrs={"class": "django_ckeditor_5"},
                config_name="extends",
            ),
            #'description': CKEditor5Widget(attrs={'placeholder': 'Enter full description here', 'class': 'django_ckeditor_5'}),
            'image': forms.ClearableFileInput(attrs={'class': 'form-control-file'}),
            
        }

class ProfilForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['sort_description', 'description', 'image', 'link_video', 'hour', 'language', 'level', 'start_date', 'end_date', 'start_enrol', 'end_enrol']

        widgets = {
            'sort_description': forms.TextInput(attrs={
                'placeholder': 'Enter short description here',
                'class': 'mt-2 block w-full rounded-lg border border-gray-300 bg-white py-2 px-3 shadow-sm focus:border-blue-500 focus:ring focus:ring-blue-200'
            }),
            'description': CKEditor5Widget(attrs={
                'class': 'django_ckeditor_5 mt-2 block w-full rounded-lg border border-gray-300 shadow-sm focus:border-blue-500 focus:ring focus:ring-blue-200'
            }, config_name="extends"),
            'image': forms.ClearableFileInput(attrs={
                'class': 'mt-2 block w-full text-gray-600 file:border file:border-gray-300 file:rounded-lg file:px-4 file:py-2 file:text-sm file:font-medium file:bg-blue-50 hover:file:bg-blue-100'
            }),
            'link_video': forms.URLInput(attrs={
                'placeholder': 'Enter video URL here',
                'class': 'mt-2 block w-full rounded-lg border border-gray-300 bg-white py-2 px-3 shadow-sm focus:border-blue-500 focus:ring focus:ring-blue-200'
            }),
            'hour': forms.NumberInput(attrs={
                'placeholder': 'Hours',
                'class': 'mt-2 block w-1/4 rounded-lg border border-gray-300 bg-white py-2 px-3 shadow-sm focus:border-blue-500 focus:ring focus:ring-blue-200'
            }),
            'language': forms.Select(attrs={
                'class': 'mt-2 block w-1/3 rounded-lg border border-gray-300 bg-white py-2 px-3 shadow-sm focus:border-blue-500 focus:ring focus:ring-blue-200'
            }),
            'level': forms.Select(choices=[
                ('beginner', 'Beginner'),
                ('intermediate', 'Intermediate'),
                ('advanced', 'Advanced')
            ], attrs={
                'class': 'mt-2 block w-1/3 rounded-lg border border-gray-300 bg-white py-2 px-3 shadow-sm focus:border-blue-500 focus:ring focus:ring-blue-200'
            }),
            'start_date': forms.DateInput(attrs={
                'type': 'date',
                'class': 'mt-2 block w-1/4 rounded-lg border border-gray-300 bg-white py-2 px-3 shadow-sm focus:border-blue-500 focus:ring focus:ring-blue-200'
            }),
            'end_date': forms.DateInput(attrs={
                'type': 'date',
                'class': 'mt-2 block w-1/4 rounded-lg border border-gray-300 bg-white py-2 px-3 shadow-sm focus:border-blue-500 focus:ring focus:ring-blue-200'
            }),
            'start_enrol': forms.DateInput(attrs={
                'type': 'date',
                'class': 'mt-2 block w-1/4 rounded-lg border border-gray-300 bg-white py-2 px-3 shadow-sm focus:border-blue-500 focus:ring focus:ring-blue-200'
            }),
            'end_enrol': forms.DateInput(attrs={
                'type': 'date',
                'class': 'mt-2 block w-1/4 rounded-lg border border-gray-300 bg-white py-2 px-3 shadow-sm focus:border-blue-500 focus:ring focus:ring-blue-200'
            }),
        }

    def clean(self):
        cleaned_data = super().clean()
        start_date = cleaned_data.get('start_date')
        end_date = cleaned_data.get('end_date')
        start_enrol = cleaned_data.get('start_enrol')
        end_enrol = cleaned_data.get('end_enrol')
        today = date.today()

        # 1️⃣ start_date minimal hari ini
        if start_date and start_date < today:
            self.add_error('start_date', "Start date cannot be earlier than today.")

        # 2️⃣ start_enrol minimal 3 hari setelah start_date
        if start_enrol and start_date:
            min_start_enrol = start_date + timedelta(days=3)
            if start_enrol < min_start_enrol:
                self.add_error('start_enrol', f"Enrollment start date must be at least 3 days after course start date ({min_start_enrol}).")

        # 3️⃣ end_enrol tidak boleh lebih dari end_date
        if end_enrol and end_date:
            if end_enrol > end_date:
                self.add_error('end_enrol', "Enrollment end date cannot be after course end date.")

        return cleaned_data

    def __init__(self, *args, **kwargs):
        super(ProfilForm, self).__init__(*args, **kwargs)

    
def save(self, commit=True):
    course = super(ProfilForm, self).save(commit=False)

    if self.cleaned_data.get('image') and course.pk:
        old_course = Course.objects.get(pk=course.pk)
        old_image_path = old_course.image.name  # Simpan path lama
        if old_course.image != self.cleaned_data['image']:
            old_course.delete_old_image()
    else:
        old_image_path = None

    if self.cleaned_data.get('image'):
        image_file = self.cleaned_data['image']
        image = PILImage.open(image_file)

        image = image.resize((1200, 628), PILImage.Resampling.LANCZOS)
        image_io = io.BytesIO()
        image.save(image_io, format='WEBP', quality=100)
        image_io.seek(0)

        while image_io.tell() > 100 * 1024:
            image_io.seek(0)
            image.save(image_io, format='WEBP', quality=90)
            image_io.seek(0)

        # Gunakan nama dan path lama jika ada
        if old_image_path:
            base_dir = os.path.dirname(old_image_path)  # direktori lama
            new_image_name = os.path.splitext(os.path.basename(old_image_path))[0] + '.webp'
            final_path = os.path.join(base_dir, new_image_name)
        else:
            new_image_name = image_file.name.rsplit('.', 1)[0] + '.webp'
            final_path = new_image_name  # akan disimpan di path default

        webp_image_file = ContentFile(image_io.read(), name=final_path)
        course.image.save(webp_image_file.name, webp_image_file, save=False)

    if commit:
        course.save()

    return course
class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['course_name', 'course_number', 'course_run', 'slug', 'category', 'level',  'org_partner']
       # fields = ['course_name', 'course_number', 'course_run', 'org_partner', 'instructor', 'status_course', 'description']
        
        widgets = {
            "course_name": forms.TextInput(attrs={
                "id": "id_title",
                "placeholder": "Full Stack Development",
                "class": "w-full px-4 py-2.5 border border-gray-300 rounded-lg rounded-lg focus:ring-2 focus:ring-blue-400",
            }),
            "slug": forms.HiddenInput(attrs={
                "id": "id_slug"
            }),
            "course_number": forms.TextInput(attrs={
                "placeholder": "CS201",
                "class": "w-full px-4 py-2.5 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-400 focus:border-transparent transition"
            }),
            "course_run": forms.TextInput(attrs={
                "placeholder": "2023",
                "class": "w-full px-4 py-2.5 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-400 focus:border-transparent transition"
            }),
            "org_partner": forms.Select(attrs={
                "class": "w-full px-4 py-2.5 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-400 focus:border-transparent transition"
            }),
            "category": forms.Select(attrs={
                "class": "w-full px-4 py-2.5 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-400 focus:border-transparent transition"
            }),
            "level": forms.Select(attrs={
                "class": "w-full px-4 py-2.5 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-400 focus:border-transparent transition"
            }),
        }
    
    def __init__(self, *args, **kwargs):

        user = kwargs.pop('user', None)  # Get the logged-in user from the view

        super().__init__(*args, **kwargs)

        # Tambahkan link ke label category
        self.fields['category'].label = mark_safe(
            'Category (<a href="/category/add/" target="_blank" class="text-blue-600 hover:underline">add new category</a>)'
        )

        if user:

            if user.is_superuser or getattr(user, 'is_curation', False):

                # Admin: Show all partners in the dropdown

                self.fields['org_partner'].queryset = Partner.objects.all()
              
            elif user.is_partner:

                # Partner: Show only their own partner

                self.fields['org_partner'].queryset = Partner.objects.filter(user=user)
                
            elif user.is_instructor:

                # Instructor: Show only the partner they are associated with

                instructor = user.instructors.first()  # Get the first instructor instance

                if instructor:

                    self.fields['org_partner'].queryset = Partner.objects.filter(id=instructor.provider.id)
                    
                else:

                    self.fields['org_partner'].queryset = Partner.objects.none()  # No options if no instructor found

            else:

                # Optionally handle other user types or set a default queryset

                self.fields['org_partner'].queryset = Partner.objects.none()  # No options for other users
    def save(self, commit=True):
        instance = super().save(commit=False)

        if not instance.slug:
            from django.utils.text import slugify
            instance.slug = slugify(instance.course_name)

        if commit:
            instance.save()
        return instance 

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']
        widgets = {
            'name': forms.TextInput(attrs={
                'placeholder': 'Enter category name here',
                'class': 'w-1/2 border border-gray-300 rounded-md px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500',
                'maxlength': '100',
            }),
        }


    def clean_name(self):
        name = self.cleaned_data.get('name', '').strip()
        # validasi tambahan: pastikan tidak lebih dari 100 karakter
        if len(name) > 100:
            raise forms.ValidationError("Category name cannot exceed 100 characters.")
        return name

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.slug = slugify(instance.name)
        if commit:
            instance.save()
        return instance


class PartnerForm(forms.ModelForm):
    user = forms.ModelChoiceField(
        queryset=CustomUser.objects.none(),
        widget=autocomplete.ModelSelect2(
            url='courses:user-autocomplete',
            attrs={'class': 'w-full px-3 py-2 text-sm border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent bg-white'}
        )
    )

    name = forms.ModelChoiceField(
        queryset=Universiti.objects.none(),
        widget=autocomplete.ModelSelect2(
            url='courses:universiti-autocomplete',
            attrs={'class': 'w-full px-3 py-2 text-sm border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent bg-white'}
        )
    )

    class Meta:
        model = Partner
        fields = ['name', 'user', 'phone', 'tax', 'iceiprice', 'logo', 'address', 'description']
        widgets = {
            "phone": forms.TextInput(attrs={
                "placeholder": "Phone Number",
                "class": (
                    "w-full px-3 py-2 text-sm border border-gray-300 rounded-md "
                    "focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                ),
            }),

            "address": forms.Textarea(attrs={
                "placeholder": "Address",
                "class": (
                    "w-full px-3 py-2 text-sm border border-gray-300 rounded-md resize-y "
                    "focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                ),
                "rows": 3,
            }),

            "description": CKEditor5Widget(
                attrs={"class": "w-full django_ckeditor_5"},
                config_name="extends",
            ),

            "tax": forms.NumberInput(attrs={
                "placeholder": "Tax Number",
                "class": (
                    "w-full px-3 py-2 text-sm border border-gray-300 rounded-md "
                    "focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                ),
                "min": "0",
            }),

            "iceiprice": forms.NumberInput(attrs={
                "placeholder": "Ice Price (%)",
                "class": (
                    "w-full px-3 py-2 text-sm border border-gray-300 rounded-md "
                    "focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                ),
                "step": "0.01",
                "min": "0",
                "max": "100",
            }),

            "logo": forms.ClearableFileInput(attrs={
                "class": (
                    "w-full px-3 py-2 text-sm border border-gray-300 rounded-md "
                    "focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                ),
                "accept": "image/*",
            }),
        }


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if self.instance.pk:
            # Jika edit, batasi queryset supaya hanya bisa memilih instance yang terkait
            if self.instance.user:
                self.fields['user'].queryset = CustomUser.objects.filter(pk=self.instance.user.pk)
            if self.instance.name:
                self.fields['name'].queryset = Universiti.objects.filter(pk=self.instance.name.pk)
        else:
            # Jika create baru, isi queryset penuh agar pilihan valid
            self.fields['user'].queryset = CustomUser.objects.all()
            self.fields['name'].queryset = Universiti.objects.all()

    def clean_user(self):
        user_value = self.cleaned_data.get('user')
        
        if not user_value:
            raise forms.ValidationError("This field is required.")
        
        if Partner.objects.filter(user=user_value).exists() and (not self.instance.pk or self.instance.user != user_value):
            raise forms.ValidationError("This user already exists as a partner. Please choose another.")
        
        return user_value

    def save(self, commit=True):
        partner = super().save(commit=False)

        if self.instance.pk and self.instance.user != partner.user:
            old_user = self.instance.user
            if old_user:
                old_user.is_partner = False
                old_user.save()

        if partner.user:
            partner.user.is_partner = True
            partner.user.save()

        if commit:
            partner.save()

        return partner

    



def validate_optional_url(field_name, value):
    if value:
        validator = URLValidator()
        try:
            validator(value)
        except ValidationError:
            raise forms.ValidationError(f"URL untuk {field_name} tidak valid.")
    return value

class PartnerFormUpdate(forms.ModelForm):
    description = forms.CharField(
        widget=CKEditor5Widget()  # atau CKEditor5Widget() kalau pakai django-ckeditor-5
    )

    # Tailwind Classes (bisa diubah warnanya kapan saja)
    INPUT_CLASS = "w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-red-500 focus:border-red-500 transition outline-none"
    FILE_CLASS = "block w-full text-sm text-gray-600 file:mr-4 file:py-2.5 file:px-4 file:rounded-lg file:border-0 file:text-sm file:font-medium file:bg-red-50 file:text-red-700 hover:file:bg-red-100"
    CHECKBOX_CLASS = "w-5 h-5 text-red-600 rounded focus:ring-red-500 border-gray-300"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Terapkan Tailwind class ke semua field secara otomatis
        for field_name, field in self.fields.items():
            if field_name == 'description':
                continue  # CKEditor sudah punya styling sendiri

            if isinstance(field.widget, (forms.TextInput, forms.NumberInput, forms.EmailInput)):
                field.widget.attrs.update({'class': self.INPUT_CLASS})
            elif isinstance(field.widget, forms.Textarea):
                field.widget.attrs.update({'class': self.INPUT_CLASS + " resize-none", 'rows': 4})
            elif isinstance(field.widget, forms.FileInput):
                field.widget.attrs.update({'class': self.FILE_CLASS})
            elif isinstance(field.widget, forms.CheckboxInput):
                field.widget.attrs.update({'class': self.CHECKBOX_CLASS})
            elif isinstance(field.widget, forms.Select):
                field.widget.attrs.update({'class': self.INPUT_CLASS})

        # Placeholder biar lebih user-friendly
        self.fields['account_number'].widget.attrs.update({'placeholder': 'Contoh: 1234567890'})
        self.fields['phone'].widget.attrs.update({'placeholder': '+628123456789'})
        self.fields['npwp'].widget.attrs.update({'placeholder': '12.345.678.9-012.345'})
        self.fields['tiktok'].widget.attrs.update({'placeholder': 'https://tiktok.com/@namakamu'})
        self.fields['youtube'].widget.attrs.update({'placeholder': 'https://youtube.com/@channelmu'})
        self.fields['twitter'].widget.attrs.update({'placeholder': 'https://twitter.com/nama'})
        self.fields['facebook'].widget.attrs.update({'placeholder': 'https://facebook.com/nama'})

    class Meta:
        model = Partner
        fields = [
            'account_number', 'account_holder_name', 'bank_name', 'phone',
            'is_pkp', 'npwp', 'npwp_file', 'payment_method', 'logo',
            'address', 'description', 'tiktok', 'youtube', 'twitter', 'facebook'
        ]

    # === SEMUA CLEAN METHOD TETAP SAMA ===
    def clean_account_number(self):
        value = self.cleaned_data.get('account_number')
        if value and not value.isdigit():
            raise forms.ValidationError("Nomor rekening hanya boleh berupa angka.")
        return value

    def clean_npwp(self):
        value = self.cleaned_data.get('npwp')
        if value:
            npwp_cleaned = value.replace('.', '').replace('-', '').replace(' ', '')
            if not re.fullmatch(r'\d{15}', npwp_cleaned):
                raise forms.ValidationError("NPWP harus terdiri dari 15 digit angka.")
        return value

    def clean_npwp_file(self):
        file = self.cleaned_data.get('npwp_file')
        if file:
            if file.size > 2 * 1024 * 1024:
                raise forms.ValidationError("Ukuran file maksimal 2MB.")
            if not file.content_type in ['application/pdf', 'image/jpeg', 'image/png']:
                raise forms.ValidationError("Format file harus PDF, JPG, atau PNG.")
        return file

    def clean_phone(self):
        value = self.cleaned_data.get('phone')
        if value and not re.match(r'^\+?\d{8,15}$', value):
            raise forms.ValidationError("Format nomor telepon tidak valid. Gunakan format internasional seperti +628123456789.")
        return value

    def clean_tiktok(self):
        return validate_optional_url("TikTok", self.cleaned_data.get('tiktok'))

    def clean_youtube(self):
        return validate_optional_url("YouTube", self.cleaned_data.get('youtube'))

    def clean_twitter(self):
        return validate_optional_url("Twitter", self.cleaned_data.get('twitter'))

    def clean_facebook(self):
        return validate_optional_url("Facebook", self.cleaned_data.get('facebook'))

class InstructorForm(forms.ModelForm):
    provider = forms.ModelChoiceField(
        queryset=Partner.objects.none(),
        widget=autocomplete.ModelSelect2(
            url='courses:partner-autocomplete',
            attrs={
                'class': 'w-full border-gray-300 rounded-lg focus:ring-blue-500 focus:border-blue-500',
                'data-placeholder': 'Type to search institution...',
            }
        ),
        label="Select Your Institution"
    )

    expertise = forms.CharField(
        label="Your Area of Expertise",
        widget=CKEditor5Widget(config_name='extends'),
        required=False
    )

    class Meta:
        model = Instructor
        fields = ['bio', 'expertise', 'experience_years', 'provider', 'agreement', 'tech']
        labels = {
            'bio': 'Tell us about yourself',
            'experience_years': 'Years of Experience',
            'tech': 'Technology Stack (URL)',
            'agreement': 'I agree to the terms and conditions',
        }
        widgets = {
            'bio': forms.Textarea(attrs={
                'class': 'w-full border border-gray-300 rounded-lg p-3 shadow-sm focus:ring-blue-500 focus:border-blue-500',
                'rows': 4,
                'placeholder': 'Write a short professional biography...',
            }),
            'experience_years': forms.NumberInput(attrs={
                'class': 'w-full border border-gray-300 rounded-lg p-3 focus:ring-blue-500 focus:border-blue-500',
                'placeholder': 'Enter total years of experience',
                'min': 0,
            }),
            'tech': forms.URLInput(attrs={
                'class': 'w-full border border-gray-300 rounded-lg p-3 focus:ring-blue-500 focus:border-blue-500',
                'placeholder': 'https://your-stack-profile.com',
            }),
            'agreement': forms.CheckboxInput(attrs={
                'class': 'h-5 w-5 text-blue-600 border-gray-300 rounded focus:ring-blue-500',
            }),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # memastikan autocomplete menampilkan pilihan yang benar
        if self.instance.pk and self.instance.provider:
            self.fields['provider'].queryset = Partner.objects.filter(pk=self.instance.provider.pk)
        else:
            self.fields['provider'].queryset = Partner.objects.all()

        # Tambahkan default Tailwind class untuk semua field kecuali checkbox
        for name, field in self.fields.items():
            widget = field.widget

            if widget.__class__.__name__ != 'CheckboxInput':
                widget.attrs.setdefault(
                    'class',
                    'w-full border border-gray-300 rounded-lg p-3 focus:ring-blue-500 focus:border-blue-500'
                )

    def clean_experience_years(self):
        experience = self.cleaned_data.get('experience_years')
        if experience is not None and experience < 0:
            raise forms.ValidationError("Experience cannot be negative. Please enter a valid number.")
        return experience

    def clean_expertise(self):
        data = self.cleaned_data.get('expertise')
        if not data or len(data.strip()) < 10:
            raise forms.ValidationError("Please describe your expertise in at least 10 characters.")
        return data

 
#instructor add coruse
class InstructorAddCoruseForm(forms.ModelForm):

    class Meta:

        model = Course

        fields = ['instructor']

        widgets = {

            'instructor': forms.Select(attrs={'class': 'form-control', 'placeholder': 'Enter instructor name'}),

        }



# forms.py


class TeamMemberForm(forms.ModelForm):
    email = forms.EmailField(
        required=True,
        label="Email Anggota Tim",
        widget=forms.EmailInput(attrs={
            'placeholder': 'contoh@email.com',
            'autocomplete': 'email'
        })
    )

    # Tailwind class (sama persis seperti form Partner biar konsisten)
    INPUT_CLASS = "w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-red-500 focus:border-red-500 transition outline-none"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].widget.attrs['class'] = self.INPUT_CLASS

    class Meta:
        model = TeamMember
        fields = ['email']

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if not CustomUser.objects.filter(email__iexact=email).exists():
            raise forms.ValidationError("Email ini tidak terdaftar di sistem. Pastikan user sudah memiliki akun.")
        
        # Cek apakah sudah ada di tim (opsional, biar tidak duplicate)
        if TeamMember.objects.filter(email__iexact=email).exists():
            raise forms.ValidationError("User dengan email ini sudah tergabung dalam tim.")
        
        return email
    


class CourseTeamForm(forms.ModelForm):
    user = forms.ModelChoiceField(
        queryset=CustomUser.objects.none(),
        widget=autocomplete.ModelSelect2(
            url='courses:user-autocomplete',  # pastikan nama url ini benar di urls.py
            forward=['course'],  # kirim course instance ke autocomplete view
            attrs={
                'class': 'tailwind-select block w-full border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500',
                'data-placeholder': 'search username...',
                'data-minimum-input-length': 2,
                'data-dropdown-auto-width': 'true',
                'data-width': 'resolve',
                'style': 'height:2.5rem;',  # naikkan tinggi input
                
            }
        ),
        label="Pengguna",
    )

    class Meta:
        model = CourseTeam
        fields = ['user', 'role']

    def __init__(self, *args, **kwargs):
        self.course = kwargs.pop('course', None)  # course object (bukan ID)
        super().__init__(*args, **kwargs)

        # UPDATE QUERYSERT DI SINI → ini yang bikin "Select a valid choice" hilang!
        if self.course:
            self.fields['user'].queryset = CustomUser.objects.exclude(
                course_teams__course=self.course
            )
        else:
            self.fields['user'].queryset = CustomUser.objects.none()

        # Styling role
        self.fields['role'].widget.attrs.update({
            'class': 'block w-full py-2 px-3 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-indigo-500'
        })

    def clean_user(self):
        user = self.cleaned_data.get('user')
        if user and self.course:
            # Pakai related_name yang benar: course.teams (bukan .team)
            if self.course.teams.filter(user=user).exists():
                raise forms.ValidationError("Pengguna ini sudah tergabung dalam tim kursus ini.")
        return user

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.course = self.course
        if commit:
            instance.save()
        return instance